### ISSUE TITLE
☂️ JetBrains plugin 1.0

### ISSUE THREAD

**Issue by victor-teles** [biomejs/biome#1189]
### Description

This issue provides a high-level overview of the development of version 1.0 of the JetBrains plugin and tracks the progress of individual tasks.

## Tasks:

- [ ] https://github.com/biomejs/biome/discussions/1052
- [ ] Enable support for textDocument/formatting in IDEs >2023.3 (https://youtrack.jetbrains.com/issue/IDEA-334150)
- [ ] Run the binary without NodeJs interpreter (This is needed to run native binaries when a custom binary path is set)
- [ ] Improve the footer status widget actions
 - `Configure Biome`
 - `Restart Biome Service`
- [ ] Support for Yarn PnP

## Repository tasks

- [ ] Add plugin version validation to GitHub workflows
- [ ] Add automatic changelog to plugin's release notes
- [ ] Move the plugin to its own repository

**Want to contribute?** Let us know if you are interested! We will assign you to the task to prevent several people from working on the same issue. Don't worry, we can unassign you later if you are no longer interested in the task! Read our [intellij contributing guide](https://github.com/biomejs/biome/blob/main/CONTRIBUTING.md?rgh-link-date=2023-08-23T12%3A52%3A31Z#intellij-plugin-development)

Are we missing something? let us know 👇

**Comment by nhedger** [comment]
I will help with moving the plugin to its own repository.

**Comment by nhedger** [comment]
What do you mean by:

> Add plugin version validation to GitHub workflows

**Comment by victor-teles** [comment]
@nhedger 

> What do you mean by:

The JetBrains plugin has a gradle task called "IntelliJ Plugin Verifier" It check for incompatibilities with new APIs / new IDE versions. 

If you are also interested in this task, there is [preliminary work done by JetBrains](https://github.com/JetBrains/intellij-platform-plugin-template/blob/8129b8c749715a0468c4b5641e6da32d7d58e8db/.github/workflows/build.yml#L174)

For more details: https://plugins.jetbrains.com/docs/intellij/verifying-plugin-compatibility.html

**Comment by nhedger** [comment]
Thanks for the explanation, I'll see if we can run this as a separate workflow on a schedule

**Comment by nhedger** [comment]
I'll also be taking on the changelog generation.
