### ISSUE TITLE
☂️ Grit runtime

### ISSUE THREAD

**Issue by arendjr** [biomejs/biome#2461]
## Description

In order to run GritQL plugins in Biome, we need to implement a Grit runtime.

We will showcase the ability of our Grit runtime using a relatively straight-forward `biome search` command, which will be functionally similar to `git grep`: Where `git grep` uses regular expressions to search through all files in a Git repository, `biome search` will use Grit patterns to search through all files in a Biome project.

If this effort is successful, we can proceed with using the runtime for plugins. To see how this issue fits into our plugin efforts, please look at the overview here: https://github.com/biomejs/biome/issues/2463

## Tasks

- [x] https://github.com/biomejs/biome/pull/1998
- [x] Refactor the GritQL engine to be free of TreeSitter dependencies. **DONE:** https://github.com/getgrit/gritql/pulls?q=is%3Apr+author%3Aarendjr
- [ ] [Implement Biome bindings to the GritQL engine](https://github.com/biomejs/biome/issues/2582) (**IN PROGRESS**)
- [x] Finish up the `biome search` command
    - [x] https://github.com/biomejs/biome/pull/2194
    - [x] Invoke the Grit engine inside the `search` command
    - [x] https://github.com/biomejs/biome/issues/2462
    - [x] Improve diagnostics (invalid query, no results, …)

## How to Contribute

Everyone is welcome to contribute pieces here! If you'd like to tackle something, please leave a comment below this issue for which item(s) of the checklist below you'd like to pick up. We will create a separate issue and assign it to you to simplify tracking.

If you need any help or have any questions about our plugin efforts in Biome, feel free to ask in the `#plugins` channel in Discord.

## Funding

To support this effort, please consider sponsoring Biome within our [Open Collective](https://opencollective.com/biome) or [GitHub sponsorship](https://github.com/sponsors/biomejs).

We decide not to fund this issue with Polar.sh because it is a long term effort. Polar.sh is designed for short and medium term efforts. It sets a deadline of 6 months to complete a task.

**Comment by arendjr** [comment]
I am going to close this issue as completed, since even though there are still minor ongoing efforts towards improving our bindings, I think at this point we can confidently say we have a Grit runtime :)
