### ISSUE TITLE
☂️ JavaScript plugin runtime

### ISSUE THREAD

**Issue by arendjr** [biomejs/biome#2469]
## Description

In order to run JavaScript plugins in Biome, we need to implement a runtime. This issue focuses on tasks needed to implement basic linter rules in JS plugins.

## How to Contribute

Everyone is welcome to contribute pieces here! If you'd like to tackle something, please leave a comment below this issue for which item(s) of the checklist below you'd like to pick up. We will create a separate issue and assign it to you to simplify tracking.

> [!NOTE]
> In order to have the issue assigned to you, you must comment on this issue.

Please only pick a single piece or group to work on at a time, and try to have time available to work on the piece when you select it so that we can keep progressing quickly. If you need any help or have any questions about our plugin efforts in Biome, feel free to ask in the `#plugins` channel in Discord.

## Tasks

- [ ] Prerequisite: https://github.com/biomejs/biome/issues/2458
- [ ] Load script and evaluate inside JS engine
    - Proof of concept can be as simple as displaying "Hello, World" in the terminal
    - Please look at the following discussion for a suitable choice of engine: https://github.com/biomejs/biome/discussions/2467
- [ ] Use transpilation to support TypeScript scripts
    - We already have [biome_js_transform crate](https://github.com/biomejs/biome/tree/main/crates/biome_js_transform) you can use
- [ ] Create an API to emit diagnostics from JS
- [ ] Create an API to register callbacks for node traversal in JS
- [ ] Create an API for transformations, so we can implement fixers in JS

## Notes

- The [plugin RFC](https://github.com/biomejs/biome/discussions/1762) has some suggestions for APIs, though it's no more than a "mockup". We will need more concrete API designs when we get to the latter tasks. Feel free to more proposals!

**Comment by axetroy** [comment]
For reference only, It may help
https://marvinh.dev/blog/speeding-up-javascript-ecosystem-part-11

**Comment by arendjr** [comment]
Just wanted to point out that this article seems to be referring to Biome when they write:

> Some tooling developers even go so far as ditching JavaScript entirely and favouring some form of query language like [GritQL](https://docs.grit.io/tutorials/gritql) as a way to extend their tools.

However, if you look at our [plugin proposal RFC](https://github.com/biomejs/biome/discussions/1762) you can see we never intended to ditch JS and instead see GritQL as a stepping stone towards implementing more efficient JS plugins.

The blog post describes a method of reducing serialisation overhead, but they still need to serialise the entire AST for every file they want to run a plugin on. Our idea is to use GritQL so that when we introduce our JS plugins, we only need to serialise those parts of JS files on which the GritQL snippet has already found a match. And then we can use the approach outlined in the blog post to serialise such snippets as cheaply as possible.
