### ISSUE TITLE
☂️ Road to Biome v2.0

### ISSUE THREAD

**Issue by ematipico** [biomejs/biome#3727]
## Tasks

We will use this issue to track all the necessary breaking changes and removal of deprecation we plan to do for the next major of Biome.

### Biome related

- [x] #4243
- [x] #4251
- [x] #4256
- [x] #4267
- [x] #4288
- [x] ~~**BREAKING**: Remove the deprecated support of `root_path` from the LSP @nhedger~~
- [x] #4269
- [x] #4767
- [x] #2986
- [x] #3619
- [x] #4813
- [x] #4812
- [ ] ~~#2228~~
- [x] #4293
- [x] #4776
- [x] #3946
- [x] #3297
- [ ] Revisit our versioning philosophy? A major is the best time to do that.
- [x] #4385
- [x] #4716
- [ ] Remove dynamic regex (`RegExep("", "")`) support in regex-related rules (`noControlCharacterInRegex` and `noMisleadingCharacterClass`)
      - `noMultipleSpacesInRegularExpressionLiterals` -> `noMultipleSpacesInRegex`
      - `noUnusedTemplateLiteral` -> `noUselessTemplateLiteral`?
- [x] ~Think about adopting the same defaults as Prettier for our options to make migration easier. Notably, `indentStyle`.~
- [x] https://github.com/biomejs/biome/issues/1918
- [x] https://github.com/biomejs/biome/issues/2312
- [x] ~~https://github.com/biomejs/biome/issues/2000~~
- [x] #4370
- [x] #4366
- [x] https://github.com/biomejs/biome/issues/3977
	**BREAKING** 	
- [x] #4359
- [x] #4296
- [x] #4305
- [x] #4569
- [x] #4375
- [x] #4832
- [x] #3307
- [x] #4626 
- [x] #4662
- [x] #4667
- [x] #4668
- [x] #4936
- [x] #4942
- [x] Make `organizeImports` a full-fledged assist action
- [x] #4892

### Infrastructure and community related

These tasks are for the great Biome community and infrastrcture.

- [x] ~~Use [`knope`](https://knope.tech/) for automated release process~~ We moved to changesets, and it's been set up
- [x] Create a `chat.biomejs.dev` sub-domain, create a redirect to the discord invite link, and change all the occurrences to use `chat.biomejs.dev` 

## Developments

- For anyone who has the right to modify the issue, please add additional tasks to the list.
- We plan to merge changes to the `next` branch, and regularly rebase `main` into `next` until we reach a point where we can merge `next` into `main`.
- We will regularly rebase `main` into `next`. Please **DOT NOT USE `git merge`**. Please use _`git rebase`_
- For anyone involved in the developments, please enable [`git rerere`](https://git-scm.com/book/en/v2/Git-Tools-Rerere) for your sanity. This feature will cache all the conflict resolutions on your local machine, so next time you happen to have the same resolution, git will apply it automatically. Very useful when rebasing the same branch.
- Create an issue every time you start working on something, so GitHub will automatically automate the workflow (it will tick the checkbox once the issue is closed).

## Engagements with this issue

If possible, please _**refrain from commenting on this issue**_ unless you're involved with the developments. If you want to discuss a decision, please use the relative issue. If an issue doesn't exist, please use Discord, or wait for an issue to be open.

**Comment by akkadaya** [comment]
I'm new to the Biome project, I came here out of frustration from configuring ESLint in a mono-repo.

What does this mean? are `trailingComma` not allowed anymore?
> Remove the deprecated `trailingComma` option

Again, I'm new and I haven't discovered everything about this project

**Comment by ematipico** [comment]
@akkadaya thank you for using Biome!

We have two options that have a very similar name, and we deprecated the one that doesn't follow the naming convention. It will be removed

**Comment by nojaf** [comment]
> Enable .editorconfig support by default

It would be fantastic to have this enabled by default. It's unintuitive that this is set to false, requiring a `biome.json` file with the following content:

```json
{
  "formatter": {
    "useEditorconfig": true
  }
}
```

to ensure my .editorconfig file is recognized.

**Comment by ematipico** [comment]
> The v3 extension depends on `rootPath`, I'll have to check how this impacts the extension. I'll assign this task to myself.
> 
> [biomejs/biome-vscode@`f9aa112`/src/session.ts#L266-L269](https://github.com/biomejs/biome-vscode/blob/f9aa11226fd6a940f8dcbf0cb2ac951f894983b7/src/session.ts#L266-L269)

We could hold off on the change. The spec marks it as deprecated, but I have no idea if the editors out there are up to date.

**Comment by nhedger** [comment]
> > The v3 extension depends on `rootPath`, I'll have to check how this impacts the extension. I'll assign this task to myself.
> > [biomejs/biome-vscode@`f9aa112`/src/session.ts#L266-L269](https://github.com/biomejs/biome-vscode/blob/f9aa11226fd6a940f8dcbf0cb2ac951f894983b7/src/session.ts#L266-L269)
> 
> We could hold off on the change. The spec marks it as deprecated, but I have no idea if the editors out there are up to date.

As far as I know, VS Code still uses it for their own extensions so I think we could indeed hold for a bit.

**Comment by arendjr** [comment]
> Introduce a JSON formatter option that expands JSON object/array (aka lineWidth: 1)?

I think it's a good idea, but then I'd suggest the JS formatter should support the same option. It would give us another extra option compared to Prettier, but it would be a consistent way of handling this, I feel.

Something like `expandLiterals: "always" | "followSource" | "onlyIfExceedingLineWidth"`, where `followSource` is our (and Prettier's) current behavior, `"always"` would be what many people request for JSON files. `onlyIfExceedingLineWidth` is just something I think makes sense to have as well :)

**Comment by ematipico** [comment]
@arendjr I think we are discussing this in https://github.com/biomejs/biome/issues/4370 

I'll remove that from the tasks, because https://github.com/biomejs/biome/issues/4370 does cover it

**Comment by ematipico** [comment]
I removed the task to rethinking formatter defaults. While I understand the motivation, there's no need. There's the option, so discussing defaults is just... bike-shedding.

**Comment by lcswillems** [comment]
Why @ematipico is it back-shedding? Personally, each time I'm trying to replace eslint / prettier by Biome, there is a bunch of settings I need to set (the main one being to use spaces instead of tabs). If the defaults were different, I would not need to do this?

**Comment by ematipico** [comment]
@lcswillems I don't want to spur a discussion from here, so if you have some options, please create one. To answer your question, it's essentially impossible to have perfect defaults because people have opinions that differ from one to another. It all comes down to ["De gustibus"](https://en.wikipedia.org/wiki/De_gustibus_non_est_disputandum), where every opinion is legit but not a correct one.

So, instead of focusing our (the team and yours, the user) on discussing which default "is correct", we should discuss the presence of options, which are more productive for all parties.

**Comment by lcswillems** [comment]
Hey @ematipico, thanks for your answer!

It is indeed not possible to find a default that is optimal for each and every user. But it doesn't mean that there is not a default that is better than another overall, while considering the group of users.

If the defaults in Biome were chosen randomly, it would be a nightmare to use Biome. Same things for all the tools that we use in our daily life.

The reason I took my personal example was just because I believe that all the people migrating from eslint / prettier would be in my situation (and so maybe a lot of users). And so I felt it was important to keep in mind.

At the end of the day, I can understand that it might be low priority and not worth prioritizing for v2.0 or any release. But I don't think we should not care about which defaults are picked and that all the defaults are equivalent.

**Comment by ematipico** [comment]
And that's why `biome migrate prettier` and `biome migrate eslint` were created
